routes/web.php
<?php

use Illuminate\Support\Facades\Route;
// use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\LoginController;
// use App\Http\Controllers\API\ApiAuthController;   
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\BlockController;
use App\Http\Controllers\BlockjobController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\SubjobController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\TaskCommentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {return view('home');})->name('home');

Route::get('/login',[LoginController::class, 'index'])->name('login');
// Route::post('/login/api',[ApiAuthController::class, 'login']);
Route::post('/login',[LoginController::class, 'store']);

Route::post('/logout',[LogoutController::class, 'store'])->name('logout');
Route::get('/dashboard',[DashboardController::class, 'index'])->name('dashboard');

Route::namespace('App\Http\Controllers\Admin')->prefix('admin')->name('admin.')->middleware('admin')->group(function(){
    Route::resource('/users', UserController::class)->except(['show','destroy']);
});

Route::get('/blocks', [BlockController::class,'index'])->name('blocks.index');
Route::get('/blocks/create', [BlockController::class,'create'])->name('blocks.create')->middleware('admin');
Route::post('/blocks', [BlockController::class,'store'])->middleware('admin');
Route::get('/blocks/{id}/edit', [BlockController::class,'edit'])->name('blocks.edit')->middleware('admin');
Route::get('/blocks/{id}/addsubjobform', [BlockController::class,'addsubjobform'])->name('blocks.addsubjobform')->middleware('admin');
Route::post('/blocks/{id}/addsubjob', [BlockController::class,'addsubjob'])->name('blocks.addsubjob')->middleware('admin');
Route::put('/blocks/{id}', [BlockController::class,'update'])->name('blocks.update')->middleware('admin');
Route::get('/blocks/{id}', [BlockController::class,'show'])->name('blocks.show');

Route::get('/projects', [ProjectController::class,'index'])->name('projects.index');
Route::get('/projects/create', [ProjectController::class,'create'])->name('projects.create')->middleware('admin');
Route::post('/projects', [ProjectController::class,'store'])->middleware('admin');
Route::get('/projects/{id}/edit', [ProjectController::class,'edit'])->name('projects.edit')->middleware('admin');
Route::put('/projects/{id}', [ProjectController::class,'update'])->name('projects.update')->middleware('admin');
Route::get('/projects/{id}', [ProjectController::class,'show'])->name('projects.show');

Route::get('/jobs', [JobController::class,'index'])->name('jobs.index');
Route::get('/jobs/create', [JobController::class,'create'])->name('jobs.create');
Route::post('/jobs', [JobController::class,'store']);
Route::get('/jobs/{id}/edit', [JobController::class,'edit'])->name('jobs.edit');
Route::put('/jobs/{id}', [JobController::class,'update'])->name('jobs.update');

Route::get('/subjobs', [SubjobController::class,'index'])->name('subjobs.index');
Route::get('/subjobs/create', [SubjobController::class,'create'])->name('subjobs.create');
Route::post('/subjobs', [SubjobController::class,'store']);
Route::get('/subjobs/{id}/edit', [SubjobController::class,'edit'])->name('subjobs.edit');
Route::put('/subjobs/{id}', [SubjobController::class,'update'])->name('subjobs.update');

Route::get('/blockjobs/{id}/show', [BlockjobController::class,'show'])->name('blockjobs.show');
Route::get('/blockjobs/{id}/activate', [BlockjobController::class,'activate'])->name('blockjobs.activate')->middleware('admin');
Route::post('/blockjobs/{id}', [BlockjobController::class,'storeactivate'])->name('blockjobs.storeactivate')->middleware('admin');

Route::get('/blockjobs/{id}/tasks/create', [TaskController::class, 'create'])->name('tasks.create')->middleware('admin');
Route::post('/blockjobs/{id}/tasks', [TaskController::class, 'store'])->name('tasks.store')->middleware('admin');
Route::get('/tasks/{id}/edit', [TaskController::class, 'edit'])->name('tasks.edit')->middleware('admin');
Route::put('/tasks/{id}', [TaskController::class,'update'])->name('tasks.update')->middleware('admin');

Route::get('taskcomments/{id}/create', [TaskCommentController::class, 'create'])->name('taskcomments.create');
Route::post('taskcomments/{id}', [TaskCommentController::class, 'store'])->name('taskcomments.store');
Route::get('taskcomments/{id}/edit', [TaskCommentController::class, 'edit'])->name('taskcomments.edit');
Route::put('taskcomments/{id}', [TaskCommentController::class, 'update'])->name('taskcomments.update');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
// use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Tymon\JWTAuth\Contracts\JWTSubject;
use App\Models\Role;

class User extends Authenticatable implements JWTSubject
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $dates = ['deleted_at'];

    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    
    public function isAdmin()
    {

        return $this->role->name == 'admin';
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Role;
use Gate;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rule;


class UserController extends Controller
{   
    public function __construct()
    {
        $this->middleware(['auth','admin']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::with('role')->where('id','!=', 1)->get();
        // dd($users);
        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::where('name','!=','admin')->get();
        return view('admin.users.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = request()->validate([
            'email' => ['required', 'email', 'max:255', 'unique:users'],
            'name' => ['required', 'string', 'max:255'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
            'roles' =>['required']
            
        ]);
        
        // dd($request->roles);
        $user = new User();
        $user->email = $data['email'];
        $user->password = Hash::make($data['password']);
        $user->name = $data['name'];
        $user->role_id = implode(' ', $request->roles);
        
        
        if($user->save()){
            session()->flash('message', 'User '.$user->name. '  has been created');
        }
        else{
            session()->flash('message','There was an error could not create the user');
        }
        
        
        return redirect (route('admin.users.index'));
    }

    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        

        $roles = Role::where('name','!=','admin')->get();
        return view('admin.users.edit',compact('roles','user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $data = request()->validate([
            'name' => ['required', 'string', 'max:255'],            
            'email' => ['required', Rule::unique('users')->ignore($user->id)],
            'roles' =>['required']
            
        ]);
        $user->name = $data['name'];        
        $user->email = $data['email'];
        $user->role_id = implode(' ', $request->roles);
        
        
        if ($request->filled('password'))
            {$request->validate(['password' => 'min:8', 'confirmed']);
                $user->password = Hash::make($request['password']);}
            
            if($user->update()){
                session()->flash('message', 'User '.$user->name. '  has been updated');
            }
            else{
                $request->session()->flash('error','There was an error updating the user');
            } 
            
            return redirect()->route('admin.users.index');
        
    }

}

resources/views/admin/users/create.blade.php
@extends('layouts.app')

@section('content')

<div class="flex justify-center">
    <div class="w-4/12 bg-white p-6 rounden-lg">
        @if (session('status'))
            <div class="bg-red-500 p-4 rounded-lg mb-6 text-white text-center">
                {{ session('status') }}
            </div>
        @endif

        <div class="mb-4 text-center">
                
        CREATE USER
                
        </div>

        <form action="{{ route('admin.users.index') }}" method="post">
            @csrf
            
            <div class="mb-4">
                <label for="name" class="sr-only"> Name </label>
                <input type="text" name="name" id="name" placeholder="User name"
                class="bg-gray-100 border-2 w-full p-4 rounded-lg @error('name') border-red-500 @enderror" value="{{ old('name') }}">
                @error('name')
                    <div class="text-red-500 mt-2 text-sm">
                        {{ $message }}
                    </div>
                @enderror
            </div>                   
            <div class="mb-4">
                <label for="email" class="sr-only"> Email </label>
                <input type="text" name="email" id="email" placeholder="User email"
                class="bg-gray-100 border-2 w-full p-4 rounded-lg @error('email') border-red-500 @enderror" value="{{ old('email') }}">
                @error('email')
                    <div class="text-red-500 mt-2 text-sm">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="mb-4">
                <label for="roles" class=""> Roles </label>
                <div class="">
                    @foreach ($roles as $role)
                        <div class="form-check">
                            <input type="radio" name="roles[]" value=" {{ $role->id }} ">
                            <label> {{ $role->name }} </label>                        
                        </div>
                    @endforeach
                </div>
            </div>
            <!-- <script>
                $(document).ready(function(){
                    $('input:checkbox').on('change',function() {
                        $('input:checkbox').not(this).prop('checked', false);
                    });
                });
            </script> -->
            <div class="mb-4">
                <label for="password" class="sr-only"> Password </label>
                <input type="password" name="password" id="password" placeholder="Password"
                class="bg-gray-100 border-2 w-full p-4 rounded-lg @error('password') border-red-500 @enderror" value="">
                @error('password')
                    <div class="text-red-500 mt-2 text-sm">
                        {{ $message }}
                    </div>
                @enderror
            </div> 

            <div class="mb-4">
                <label for="password_confirmation" class="sr-only"> Confirm Password </label>
                <input type="password" name="password_confirmation" id="password_confirmation" placeholder="Confirm Password"
                class="bg-gray-100 border-2 w-full p-4 rounded-lg @error('password_confirmation') border-red-500 @enderror" value="">
                @error('password_confirmation')
                    <div class="text-red-500 mt-2 text-sm">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            
            <div>
                <button type="submit" class="bg-blue-500 text-white px-4 py-3
                rounded font-medium w-full focus:outline-none hover:bg-indigo-600 rounded"> Create </button>
            </div>           
        </form>
    </div>
</div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="flex justify-center">
    <div class="w-4/12 bg-white p-6 rounden-lg">  
        @if (session('status'))
            <div class="bg-red-500 p-4 rounded-lg mb-6 text-white text-center">
                {{ session('status') }}
            </div>
        @endif

        <div class="mb-4 text-center">
                
        EDIT USER
                
        </div>

        <form action="{{ route('admin.users.update', $user ?? '') }} " method="post">
            @csrf
            @method('PUT')
            
            <div class="mb-4">
                <label for="name" class="sr-only"> Name </label>
                <input type="text" name="name" id="name" placeholder="User name"
                class="bg-gray-100 border-2 w-full p-4 rounded-lg @error('name') border-red-500 @enderror" value="{{ $user->name }}">
                @error('name')
                    <div class="text-red-500 mt-2 text-sm">
                        {{ $message }}
                    </div>
                @enderror
            </div>                   
            <div class="mb-4">
                <label for="email" class="sr-only"> Email </label>
                <input type="text" name="email" id="email" placeholder="User email"
                class="bg-gray-100 border-2 w-full p-4 rounded-lg @error('email') border-red-500 @enderror" value="{{ $user->email }}">
                @error('email')
                    <div class="text-red-500 mt-2 text-sm">
                        {{ $message }}
                    </div>
                @enderror
            </div>            
            

            <div class="mb-4">
                <label for="roles" class=""> Roles </label>
                <div class="">
                    @foreach ($roles as $role)
                        <div class="form-check">
                            <input type="radio" name="roles[]" value="{{ $role->id }}" 
                                {{ $user->role->name == $role->name ? 'checked' : ''  }} >
                            <label> {{ $role->name }} </label>                        
                        </div>
                    @endforeach
                </div>
            </div>

            <div class="mb-4">
                <label for="password" class="sr-only"> Password </label>
                <input type="password" name="password" id="password" placeholder="Enter new Password if change needed"
                class="bg-gray-100 border-2 w-full p-4 rounded-lg @error('password') border-red-500 @enderror" value="">
                @error('password')
                    <div class="text-red-500 mt-2 text-sm">
                        {{ $message }}
                    </div>
                @enderror
            </div> 

            <div class="mb-4">
                <label for="password_confirmation" class="sr-only"> Confirm Password </label>
                <input type="password" name="password_confirmation" id="password_confirmation" placeholder="Confirm Password"
                class="bg-gray-100 border-2 w-full p-4 rounded-lg @error('password_confirmation') border-red-500 @enderror" value="">
                @error('password_confirmation')
                    <div class="text-red-500 mt-2 text-sm">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            
            <div>
                <button type="submit" class="bg-blue-500 text-white px-4 py-3
                rounded font-medium w-full focus:outline-none hover:bg-indigo-600 rounded"> Update </button>
            </div>           
        </form>
    </div>
</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')

    @if (session()->has('message'))
        <div id="alert" class="text-white px-6 py-4 border-0 rounded relative mb-4 bg-green-500 bg-opacity-75">
            <span class="inline-block align-middle mr-8">
                {{ session('message') }}
            </span>
            <button class="absolute bg-transparent text-2xl font-semibold leading-none right-0 top-0 mt-4 mr-6 outline-none focus:outline-none" onclick="document.getElementById('alert').remove();">
                <span>×</span>
            </button>
        </div>
    @endif

<div class="flex justify-center">
    <table class="shadow-lg bg-white">
    
    <thead>
    <tr>
        <th class="bg-blue-500 bg-opacity-75 border text-left px-8 py-4">Users</th>
        <th class="bg-blue-500 bg-opacity-75 border text-left px-8 py-4">Email</th>
        <th class="bg-blue-500 bg-opacity-75 border text-left px-8 py-4">Roles</th>
        <th class="bg-blue-500 bg-opacity-75 border text-left px-8 py-4">Action</th>
    </tr>
    </thead>
    <tbody>
    @foreach ($users as $user)
    <tr>
        <td class="border px-8 py-4">{{ $user->name }}</td>
        <td class="border px-8 py-4">{{ $user->email }}</td>
        <td class="border px-8 py-4">{{ $user->role->name }}</td>
        <td class="border px-8 py-4">
            <a href="{{ route ('admin.users.edit', $user->id ) }}"> 
            <button type="button" class="bg-blue-500 text-white px-4 py-3
                rounded font-medium w-full focus:outline-none hover:bg-indigo-600 rounded">Edit</button>
            </a>
        </td>
    </tr>
    </tbody>
    @endforeach     
    </table>
</div>


<div class="flex justify-center mt-6">
<a href="{{ route('admin.users.create') }}"><button type="button" class="bg-blue-500 text-white px-60 py-3
                rounded font-medium w-full focus:outline-none hover:bg-indigo-600 rounded">Create User</button> </a>
</div>



@endsection